import { Item } from "./custom-item";

export type Gear = {
	weapons: {
		meleeWeapons: {
			unarmed: string[],
			clubs: string[],
			clades: string[],
			exoticMeleeWeapons: string[],
		},
		projectileAndThrowingWeapons: {
			throwingWeapons: string[],
			bows: string[],
			crossbows: string[],
			arrowheads: string[],
		},
		lessThanLethal: {
			tasers: string[],
			specialRangedWeapons: string[],
		},
		firearms: {
			holdOutPistols: string[],
			lightPistols: string[],
			heavyPistols: string[],
			subMachineguns: string[],
			shotguns: string[],
			assaultRifles: string[],
			sportRifles: string[],
			sniperRifles: string[],
			assaultCannons: string[],
			lightMachineguns: string[],
			mediumMachineguns: string[],
			heavyMachineguns: string[],
			ammunitionTypes: string[],
			firearmAccessories: string[],
		},
		grenadesAndRockets: {
			grenades: string[],
			grenadeLaunchers: string[],
			rockets: string[],
			rocketLaunchers: string[];
		},
	},
	clothingAndArmor: {
		clothing: string[],
		armor: string[],
		armorModifications: string[],
		helmetsAndShields: string[],
	},
	augmentations: {
		cyberAndBiowareGrades: string[],
		headware: string[],
		eyeware: string[],
		earware: string[],
		bodyware: string[],
		cyberlimbs: string[],
		cyberlimbEnhancements: string[],
		cyberlimbAccessories: string[],
		cyberMeleeWeapons: string[],
		basicBioware: string[],
		culturedBioware: string[],
	},
	tech: {
		electronics: {
			commlink: string[],
			coomlinkUpgrades: string[],
			commlinkAccessories: string[],
		},
		surveillance: {
			imagingDevicies: string[],
			imagingEnhancements: string[],
			audioDevices: string[],
			audioEnhancements: string[],
			sensorPackages: string[],
			sensorFunctions: string[],
		},
		security: {
			locks: string[],
			restraints: string[],
			breakingAndEnteringTools: string[],
			disguises: string[],
		},
		datachipsAndSoftware: {
			matrixPrograms: string[],
			skillsoftPrograms: string[],
			dataPrograms: string[],
			simsemse: string[],
			areprograms: string[],
		},
		tools: string[],
		survivalGear: string[],
		grapplegun: string[],
	},
	medicalEquipment: {
		biotech: string[],
		slapPatches: string[],
		docwagonContracts: string[],
	},
	chemicals: {
		drugs: string[],
		toxins: string[],
		compounds: string[],
	},
	explosives: {
		explosives: string[],
		detonators: string[],
	},
	magicalEquipment: {
		spellFormulae: string[],
		spellFetish: string[],
		foci: string[],
		magicalSupplies: string[],
	},
	vehiclesAndDrones: {
		bikes: string[],
		cars: string[],
		trucks: string[],
		securityVehicles: string[],
		microDroens: string[],
		miniDrones: string[],
		smallDrones: string[],
		mediumDrones: string[],
		largeDrones: string[],
		vehicleModifications: string[],
	},
};

export type AllGear = {
	weapons: {
		meleeWeapons: {
			unarmed: Item[],
			clubs: Item[],
			clades: Item[],
			exoticMeleeWeapons: Item[],
		},
		projectileAndThrowingWeapons: {
			throwingWeapons: Item[],
			bows: Item[],
			crossbows: Item[],
			arrowheads: Item[],
		},
		lessThanLethal: {
			tasers: Item[],
			specialRangedWeapons: Item[],
		},
		firearms: {
			holdOutPistols: Item[],
			lightPistols: Item[],
			heavyPistols: Item[],
			subMachineguns: Item[],
			shotguns: Item[],
			assaultRifles: Item[],
			sportRifles: Item[],
			sniperRifles: Item[],
			assaultCannons: Item[],
			lightMachineguns: Item[],
			mediumMachineguns: Item[],
			heavyMachineguns: Item[],
			ammunitionTypes: Item[],
			firearmAccessories: Item[],
		},
		grenadesAndRockets: {
			grenades: Item[],
			grenadeLaunchers: Item[],
			rockets: Item[],
			rocketLaunchers: Item[];
		},
	},
	clothingAndArmor: {
		clothing: Item[],
		armor: Item[],
		armorModifications: Item[],
		helmetsAndShields: Item[],
	},
	augmentations: {
		cyberAndBiowareGrades: Item[],
		headware: Item[],
		eyeware: Item[],
		earware: Item[],
		bodyware: Item[],
		cyberlimnTypes: Item[],
		cyberlimbs: Item[],
		cyberlimbEnhancements: Item[],
		cyberlimbAccessories: Item[],
		cyberMeleeWeapons: Item[],
		basicBioware: Item[],
		culturedBioware: Item[],
	},
	tech: {
		electronics: {
			commlink: Item[],
			coomlinkUpgrades: Item[],
			commlinkAccessories: Item[],
		},
		surveillance: {
			imagingDevicies: Item[],
			imagingEnhancements: Item[],
			audioDevices: Item[],
			audioEnhancements: Item[],
			sensorPackages: Item[],
			sensorFunctions: Item[],
		},
		security: {
			locks: Item[],
			restraints: Item[],
			breakingAndEnteringTools: Item[],
			disguises: Item[],
		},
		datachipsAndSoftware: {
			matrixPrograms: Item[],
			skillsoftPrograms: Item[],
			dataPrograms: Item[],
			simsemse: Item[],
			areprograms: Item[],
		},
		tools: Item[],
		survivalGear: Item[],
		grapplegun: Item[],
	},
	medicalEquipment: {
		biotech: Item[],
		slapPatches: Item[],
		docwagonContracts: Item[],
	},
	chemicals: {
		drugs: Item[],
		toxins: Item[],
		compounds: Item[],
	},
	explosives: {
		explosives: Item[],
		detonators: Item[],
	},
	magicalEquipment: {
		spellFormulae: Item[],
		spellFetish: Item[],
		foci:Item[],
		magicalSupplies: Item[],
	},
	vehiclesAndDrones: {
		bikes: Item[],
		cars: Item[],
		trucks: Item[],
		securityVehicles: Item[],
		microDroens: Item[],
		miniDrones: Item[],
		smallDrones: Item[],
		mediumDrones: Item[],
		largeDrones: Item[],
		vehicleModifications: Item[],
	},
};